package code_generation

import (
	"fmt"
	"go/format"
	"math"
	"os"
	"reflect"
	"strconv"
	"strings"

	motmedelErrors "github.com/Motmedel/utils_go/pkg/errors"
	codeGenerationErrors "github.com/vphpersson/code_generation_go/pkg/errors"
)

var defaultPackagePath = "main"

type ImportSet map[string]struct{}

func (importSet ImportSet) Generate() string {
	if len(importSet) == 0 {
		return ""
	}

	var importEntries []string
	for importPath := range importSet {
		importEntries = append(importEntries, fmt.Sprintf("\t\"%s\"", importPath))
	}
	return fmt.Sprintf("import (\n%s\n)", strings.Join(importEntries, "\n"))
}

func GetGeneratedFilename() string {
	if gofile := os.Getenv("GOFILE"); gofile != "" {
		return strings.TrimSuffix(gofile, ".go") + "_generated.go"
	}

	return ""
}

func MakeFileContent(
	code string,
	packageName string,
	by string,
	importSet ImportSet,
) ([]byte, error) {
	outputData := []byte(
		fmt.Sprintf(
			"%spackage %s\n%s\n%s",
			fmt.Sprintf("// Code generated by %q; DO NOT EDIT.\n", by),
			packageName,
			importSet.Generate(),
			code,
		),
	)
	formattedOutputData, err := format.Source(outputData)
	if err != nil {
		return nil, motmedelErrors.NewWithTrace(fmt.Errorf("format source: %w", err), outputData)
	}

	return formattedOutputData, nil
}

func GetGeneratedFileContents(
	value any,
	packageName string,
	by string,
	variableName string,
	importSet ImportSet,
) ([]byte, error) {
	reflectValueOf := reflect.ValueOf(value)
	literal, importSet, err := GenerateLiteral(reflectValueOf, importSet)
	if err != nil {
		return nil, motmedelErrors.New(fmt.Errorf("generate literal: %w", err), reflectValueOf)
	}

	output, err := MakeFileContent(
		fmt.Sprintf("var %s = %s", variableName, literal),
		packageName,
		by,
		importSet,
	)
	if err != nil {
		return nil, motmedelErrors.New(fmt.Errorf("make file content: %w", err), literal)
	}

	return output, nil
}

func GenerateLiteral(value reflect.Value, importSet ImportSet) (string, ImportSet, error) {
	if !value.IsValid() {
		return "", nil, motmedelErrors.NewWithTrace(codeGenerationErrors.ErrInvalidValue, value)
	}

	switch value.Kind() {
	case reflect.Invalid:
		// Redundant due to IsValid check, but explicit case for clarity
		return "", nil, motmedelErrors.NewWithTrace(codeGenerationErrors.ErrInvalidValue, value)
	case reflect.Bool:
		if value.Bool() {
			return "true", importSet, nil
		}
		return "false", importSet, nil
	case reflect.String:
		return strconv.Quote(value.String()), importSet, nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return fmt.Sprint(value.Int()), importSet, nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return fmt.Sprint(value.Uint()), importSet, nil
	case reflect.Uintptr:
		// Represent as a decimal literal
		return fmt.Sprint(value.Uint()), importSet, nil
	case reflect.Float32:
		f := value.Float()
		if math.IsNaN(f) {
			if importSet == nil {
				importSet = make(map[string]struct{})
			}
			importSet["math"] = struct{}{}
			return "math.NaN()", importSet, nil
		}
		if i := math.IsInf(f, 0); i {
			if importSet == nil {
				importSet = make(map[string]struct{})
			}
			importSet["math"] = struct{}{}
			if math.IsInf(f, 1) {
				return "math.Inf(1)", importSet, nil
			}
			return "math.Inf(-1)", importSet, nil
		}
		return strconv.FormatFloat(f, 'g', -1, 32), importSet, nil
	case reflect.Float64:
		f := value.Float()
		if math.IsNaN(f) {
			if importSet == nil {
				importSet = make(map[string]struct{})
			}
			importSet["math"] = struct{}{}
			return "math.NaN()", importSet, nil
		}
		if i := math.IsInf(f, 0); i {
			if importSet == nil {
				importSet = make(map[string]struct{})
			}
			importSet["math"] = struct{}{}
			if math.IsInf(f, 1) {
				return "math.Inf(1)", importSet, nil
			}
			return "math.Inf(-1)", importSet, nil
		}
		return strconv.FormatFloat(f, 'g', -1, 64), importSet, nil
	case reflect.Complex64:
		c := value.Complex()
		r := real(c)
		i := imag(c)
		rLit, importSet2 := formatFloatWithMathImport(r, 32, importSet)
		iLit, importSet3 := formatFloatWithMathImport(i, 32, importSet2)
		return fmt.Sprintf("complex(%s, %s)", rLit, iLit), importSet3, nil
	case reflect.Complex128:
		c := value.Complex()
		r := real(c)
		i := imag(c)
		rLit, importSet2 := formatFloatWithMathImport(r, 64, importSet)
		iLit, importSet3 := formatFloatWithMathImport(i, 64, importSet2)
		return fmt.Sprintf("complex(%s, %s)", rLit, iLit), importSet3, nil
	case reflect.Struct:
		pkgPath := value.Type().PkgPath()
		// TODO: Is this check reasonable?
		if pkgPath != "" && pkgPath != defaultPackagePath {
			if importSet == nil {
				importSet = make(map[string]struct{})
			}
			importSet[pkgPath] = struct{}{}
		}
		return processStruct(value, importSet)
	case reflect.Slice, reflect.Array:
		return processSlice(value, importSet)
	case reflect.Map:
		return processMap(value, importSet)
	case reflect.Ptr:
		return processPointer(value, importSet)
	case reflect.Func:
		if !value.IsNil() {
			return "", nil, motmedelErrors.NewWithTrace(codeGenerationErrors.ErrUnsupportedFunctionFields, value)
		}
		return "nil", importSet, nil
	case reflect.Interface:
		// For interface{} values, produce a quoted string of the fmt %v representation
		return strconv.Quote(fmt.Sprintf("%v", value.Interface())), importSet, nil
	case reflect.Chan:
		if !value.IsNil() {
			return "", nil, motmedelErrors.NewWithTrace(codeGenerationErrors.ErrUnsupportedChanField, value)
		}
		return "nil", importSet, nil
	case reflect.UnsafePointer:
		return "", nil, motmedelErrors.NewWithTrace(codeGenerationErrors.ErrUnsupportedUnsafePointerField, value)
	default:
		return fmt.Sprintf("%v", value.Interface()), importSet, nil
	}
}

func processStruct(value reflect.Value, importSet ImportSet) (string, ImportSet, error) {
	typ := value.Type()

	name := typ.Name()
	pkgPath := typ.PkgPath()
	if pkgPath != defaultPackagePath {
		pkgPathSlice := strings.Split(pkgPath, "/")
		name = pkgPathSlice[len(pkgPathSlice)-1] + "." + name
	}

	result := fmt.Sprintf("%s{\n", name)
	for i := range value.NumField() {
		field := typ.Field(i)
		fieldValue := value.Field(i)

		if fieldValue.IsZero() {
			continue
		}

		var fieldLiteral string
		var err error

		fieldLiteral, importSet, err = GenerateLiteral(fieldValue, importSet)
		if err != nil {
			return "", nil, err
		}

		result += fmt.Sprintf("    %s: %s,\n", field.Name, fieldLiteral)
	}
	result += "}"
	return result, importSet, nil
}

func processSlice(value reflect.Value, importSet ImportSet) (string, ImportSet, error) {
	elements := make([]string, value.Len())
	for i := range value.Len() {
		var elemLiteral string
		var err error

		elemLiteral, importSet, err = GenerateLiteral(value.Index(i), importSet)
		if err != nil {
			return "", nil, err
		}

		elements[i] = elemLiteral
	}
	// If the slice element type is interface{}, change it to string
	elemType := value.Type().Elem()
	elemTypeStr := elemType.String()
	if elemType.Kind() == reflect.Interface {
		elemTypeStr = "string"
	}
	return fmt.Sprintf("[]%s{%s}", elemTypeStr, strings.Join(elements, ", ")), importSet, nil
}

func processMap(value reflect.Value, importSet ImportSet) (string, ImportSet, error) {
	mapKeys := value.MapKeys()
	elements := make([]string, len(mapKeys))
	for i, key := range mapKeys {
		var keyLiteral string
		var err error
		keyLiteral, importSet, err = GenerateLiteral(key, importSet)
		if err != nil {
			return "", nil, err
		}
		mapValue := value.MapIndex(key)
		var valueLiteral string
		valueLiteral, importSet, err = GenerateLiteral(mapValue, importSet)
		if err != nil {
			return "", nil, err
		}
		elements[i] = fmt.Sprintf("%s: %s", keyLiteral, valueLiteral)
	}

	elemType := value.Type().Elem()
	elemTypeStr := elemType.String()
	if elemType.Kind() == reflect.Interface {
		elemTypeStr = "string"
	}

	return fmt.Sprintf("map[%s]%s{%s}", value.Type().Key(), elemTypeStr, strings.Join(elements, ", ")), importSet, nil
}

func processPointer(value reflect.Value, importSet ImportSet) (string, ImportSet, error) {
	if value.IsNil() {
		return "nil", importSet, nil
	}

	var literal string
	var err error
	literal, importSet, err = GenerateLiteral(value.Elem(), importSet)
	if err != nil {
		return "", nil, err
	}

	return "&" + literal, importSet, nil
}

// formatFloatWithMathImport returns a Go expression for the float value, handling NaN/Inf
// by using math.NaN()/math.Inf(sign) and ensuring the math import is added when needed.
func formatFloatWithMathImport(f float64, bitSize int, importSet ImportSet) (string, ImportSet) {
	if math.IsNaN(f) {
		if importSet == nil {
			importSet = make(map[string]struct{})
		}
		importSet["math"] = struct{}{}
		return "math.NaN()", importSet
	}
	if math.IsInf(f, 0) {
		if importSet == nil {
			importSet = make(map[string]struct{})
		}
		importSet["math"] = struct{}{}
		if math.IsInf(f, 1) {
			return "math.Inf(1)", importSet
		}
		return "math.Inf(-1)", importSet
	}
	return strconv.FormatFloat(f, 'g', -1, bitSize), importSet
}

func init() {
	if goPackage := os.Getenv("GOPACKAGE"); goPackage != "" {
		defaultPackagePath = goPackage
	}
}
