package code_generation

import (
	"math"
	"reflect"
	"strings"
	"testing"
)

type localStruct struct {
	A int
	B string
	C int // zero value should be omitted
}

func TestGenerateLiteral(t *testing.T) {
	t.Parallel()
	type args struct {
		value     reflect.Value
		importSet ImportSet
	}
	tests := []struct {
		name    string
		args    args
		want    string
		want1   ImportSet
		wantErr bool
	}{
		{
			name:  "bool true",
			args:  args{value: reflect.ValueOf(true)},
			want:  "true",
			want1: nil,
		},
		{
			name:  "string quoted",
			args:  args{value: reflect.ValueOf("hello")},
			want:  "\"hello\"",
			want1: nil,
		},
		{
			name:  "int literal",
			args:  args{value: reflect.ValueOf(int(42))},
			want:  "42",
			want1: nil,
		},
		{
			name:  "float32 NaN adds math import",
			args:  args{value: reflect.ValueOf(float32(math.NaN()))},
			want:  "math.NaN()",
			want1: ImportSet{"math": {}},
		},
		{
			name:  "complex128 with Inf real adds math import",
			args:  args{value: reflect.ValueOf(complex(math.Inf(1), 2))},
			want:  "complex(math.Inf(1), 2)",
			want1: ImportSet{"math": {}},
		},
		{
			name: "struct with non-zero fields and import path",
			args: args{value: reflect.ValueOf(localStruct{A: 1, B: "x"})},
			want: "code_generation.localStruct{\n    A: 1,\n    B: \"x\",\n}",
			want1: func() ImportSet {
				// Pkg path import is added by GenerateLiteral for structs from non-main packages
				pkgPath := reflect.TypeOf(localStruct{}).PkgPath()
				return ImportSet{pkgPath: {}}
			}(),
		},
		{
			name:  "nil func literal",
			args:  args{value: reflect.ValueOf((func())(nil))},
			want:  "nil",
			want1: nil,
		},
		{
			name:    "non-nil func returns error",
			args:    args{value: reflect.ValueOf(func() {})},
			wantErr: true,
		},
		{
			name:  "nil chan literal",
			args:  args{value: reflect.ValueOf((chan int)(nil))},
			want:  "nil",
			want1: nil,
		},
		{
			name:    "non-nil chan returns error",
			args:    args{value: reflect.ValueOf(make(chan int))},
			wantErr: true,
		},
		{
			name:  "interface kind quoted",
			args:  args{value: reflect.ValueOf(new(any)).Elem()}, // zero interface value
			want:  "\"<nil>\"",
			want1: nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, got1, err := GenerateLiteral(tt.args.value, tt.args.importSet)
			if (err != nil) != tt.wantErr {
				t.Fatalf("GenerateLiteral() error = %v, wantErr %v", err, tt.wantErr)
			}
			if err == nil {
				if got != tt.want {
					t.Errorf("GenerateLiteral() got = %q, want %q", got, tt.want)
				}
				if !reflect.DeepEqual(got1, tt.want1) {
					t.Errorf("GenerateLiteral() got1 = %v, want %v", got1, tt.want1)
				}
			}
		})
	}
}

func TestGetGeneratedFileContents(t *testing.T) {
	t.Parallel()
	type args struct {
		value        any
		packageName  string
		by           string
		variableName string
		importSet    ImportSet
	}
	tests := []struct {
		name    string
		args    args
		want    []byte
		wantErr bool
	}{
		{
			name: "simple int no imports",
			args: args{value: 5, packageName: "mypkg", by: "tester", variableName: "X", importSet: nil},
			want: []byte(strings.Join([]string{
				"// Code generated by \"tester\"; DO NOT EDIT.",
				"package mypkg",
				"",
				"var X = 5",
				"",
			}, "\n")),
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, err := GetGeneratedFileContents(tt.args.value, tt.args.packageName, tt.args.by, tt.args.variableName, tt.args.importSet)
			if (err != nil) != tt.wantErr {
				t.Fatalf("GetGeneratedFileContents() error = %v, wantErr %v", err, tt.wantErr)
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("GetGeneratedFileContents() got = %q, want %q", string(got), string(tt.want))
			}
		})
	}
}

func TestGetGeneratedFilename(t *testing.T) {
	t.Setenv("GOFILE", "example.go")
	if got := GetGeneratedFilename(); got != "example_generated.go" {
		t.Fatalf("GetGeneratedFilename() with env = %q, want %q", got, "example_generated.go")
	}
}

func TestImportSet_Generate(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name      string
		importSet ImportSet
		want      string
	}{
		{
			name:      "empty",
			importSet: nil,
			want:      "",
		},
		{
			name:      "single import",
			importSet: ImportSet{"math": {}},
			want:      "import (\n\t\"math\"\n)",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			if got := tt.importSet.Generate(); got != tt.want {
				t.Errorf("Generate() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestMakeFileContent(t *testing.T) {
	t.Parallel()
	type args struct {
		code        string
		packageName string
		by          string
		importSet   ImportSet
	}
	tests := []struct {
		name    string
		args    args
		want    []byte
		wantErr bool
	}{
		{
			name: "with import and code",
			args: args{
				code:        "var X = 5",
				packageName: "mypkg",
				by:          "tester",
				importSet:   ImportSet{"math": {}},
			},
			want: []byte(strings.Join([]string{
				"// Code generated by \"tester\"; DO NOT EDIT.",
				"package mypkg",
				"",
				"import (",
				"\t\"math\"",
				")",
				"",
				"var X = 5",
				"",
			}, "\n")),
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, err := MakeFileContent(tt.args.code, tt.args.packageName, tt.args.by, tt.args.importSet)
			if (err != nil) != tt.wantErr {
				t.Fatalf("MakeFileContent() error = %v, wantErr %v", err, tt.wantErr)
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("MakeFileContent() got = %q, want %q", string(got), string(tt.want))
			}
		})
	}
}

func Test_formatFloatWithMathImport(t *testing.T) {
	t.Parallel()
	type args struct {
		f         float64
		bitSize   int
		importSet ImportSet
	}
	tests := []struct {
		name  string
		args  args
		want  string
		want1 ImportSet
	}{
		{
			name:  "normal",
			args:  args{f: 3.14, bitSize: 64},
			want:  "3.14",
			want1: nil,
		},
		{
			name:  "NaN",
			args:  args{f: math.NaN(), bitSize: 64},
			want:  "math.NaN()",
			want1: ImportSet{"math": {}},
		},
		{
			name:  "+Inf",
			args:  args{f: math.Inf(1), bitSize: 64},
			want:  "math.Inf(1)",
			want1: ImportSet{"math": {}},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, got1 := formatFloatWithMathImport(tt.args.f, tt.args.bitSize, tt.args.importSet)
			if got != tt.want {
				t.Errorf("formatFloatWithMathImport() got = %q, want %q", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("formatFloatWithMathImport() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}

func Test_processMap(t *testing.T) {
	t.Parallel()
	type args struct {
		value     reflect.Value
		importSet ImportSet
	}
	tests := []struct {
		name    string
		args    args
		want    string
		want1   ImportSet
		wantErr bool
	}{
		{
			name:  "simple map",
			args:  args{value: reflect.ValueOf(map[string]int{"a": 1})},
			want:  "map[string]int{\"a\": 1}",
			want1: nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, got1, err := processMap(tt.args.value, tt.args.importSet)
			if (err != nil) != tt.wantErr {
				t.Fatalf("processMap() error = %v, wantErr %v", err, tt.wantErr)
			}
			if got != tt.want {
				t.Errorf("processMap() got = %q, want %q", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("processMap() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}

func Test_processPointer(t *testing.T) {
	t.Parallel()
	type args struct {
		value     reflect.Value
		importSet ImportSet
	}
	tests := []struct {
		name    string
		args    args
		want    string
		want1   ImportSet
		wantErr bool
	}{
		{
			name:  "nil pointer",
			args:  args{value: reflect.ValueOf((*int)(nil))},
			want:  "nil",
			want1: nil,
		},
		{
			name: "non-nil pointer",
			args: func() args {
				v := 5
				return args{value: reflect.ValueOf(&v)}
			}(),
			want:  "&5",
			want1: nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, got1, err := processPointer(tt.args.value, tt.args.importSet)
			if (err != nil) != tt.wantErr {
				t.Fatalf("processPointer() error = %v, wantErr %v", err, tt.wantErr)
			}
			if got != tt.want {
				t.Errorf("processPointer() got = %q, want %q", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("processPointer() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}

func Test_processSlice(t *testing.T) {
	t.Parallel()
	type args struct {
		value     reflect.Value
		importSet ImportSet
	}
	tests := []struct {
		name    string
		args    args
		want    string
		want1   ImportSet
		wantErr bool
	}{
		{
			name:  "ints",
			args:  args{value: reflect.ValueOf([]int{1, 2, 3})},
			want:  "[]int{1, 2, 3}",
			want1: nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, got1, err := processSlice(tt.args.value, tt.args.importSet)
			if (err != nil) != tt.wantErr {
				t.Fatalf("processSlice() error = %v, wantErr %v", err, tt.wantErr)
			}
			if got != tt.want {
				t.Errorf("processSlice() got = %q, want %q", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("processSlice() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}

func Test_processStruct(t *testing.T) {
	t.Parallel()
	type args struct {
		value     reflect.Value
		importSet ImportSet
	}
	tests := []struct {
		name    string
		args    args
		want    string
		want1   ImportSet
		wantErr bool
	}{
		{
			name:  "local struct adds pkg prefix and omits zero field",
			args:  args{value: reflect.ValueOf(localStruct{A: 1, B: "y"})},
			want:  "code_generation.localStruct{\n    A: 1,\n    B: \"y\",\n}",
			want1: nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, got1, err := processStruct(tt.args.value, tt.args.importSet)
			if (err != nil) != tt.wantErr {
				t.Fatalf("processStruct() error = %v, wantErr %v", err, tt.wantErr)
			}
			if got != tt.want {
				t.Errorf("processStruct() got = %q, want %q", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("processStruct() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}
